### ISSUE TITLE
Zeilenumbrüche

### ISSUE THREAD

**Issue by Magikarpm** [kit-sdq/Artemis#15]
### Describe the bug

Zeilenumbrüche werde gespeichert aber nicht angezeigt.

### To Reproduce

1. Feedback hinzufügen
2. Zeilenumbruch machen.
3. Feedback speichern.

### Expected behavior

Dass der Zeilenumbruch sichtbar ist.

### What browsers are you seeing the problem on?

Chrome

**Comment by dfuchss** [comment]
I think you refer to this upstream issue https://github.com/ls1intum/Artemis/issues/3854 , right?
